version: '3'

services:
  nginx:
    image: nginx:latest
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=memory.vickypr.es
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=memory.vickypr.es
      - LETSENCRYPT_EMAIL=admin@gmail.com
    volumes:
      - /home/ubuntu/memory:/usr/share/nginx/html:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: nginx-proxy
    external: true